In [73]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_blobs
from sklearn.model_selection import cross_val_score
import numpy as np

In [4]:
train_x = np.load("s1_train_x_preprocess.npy")
train_y = np.load("s1_train_y.npy")
test_x = np.load("s1_test_x_preprocess.npy")

In [109]:
train_x = np.load("s1_train_x_no_preprocess.npy")
train_y = np.load("s1_train_y.npy")
test_x = np.load("s1_test_x_no_preprocess.npy")

In [110]:
res = []
for i in train_y:
    res.append(i - 101)
res = np.array(res)

In [111]:
res

array([ 1,  3,  6, 11, 14, 16, 18, 21, 25, 29, 32, 34], dtype=int64)

In [123]:
classifier = RandomForestClassifier(n_estimators=30, max_depth=None,
...     min_samples_split=2, random_state=0)

In [113]:
train_x.shape

(12, 5, 510, 20)

In [114]:
t = train_x[0]

In [115]:
x = []
y = []
for k in range(len(train_x)):
    temp = []
    for i in t:
        total = i[:, 0].reshape(-1, 1)
        for j in range(1, 20):
            total = np.row_stack((total, i[:, j].reshape(-1, 1)))
        temp.append(total.reshape(-1))
    temp = np.array(temp).reshape(-1)
    x.append(temp)
    y.append(res[k])
x = np.array(x)
y = np.array(y)

In [116]:
y

array([ 1,  3,  6, 11, 14, 16, 18, 21, 25, 29, 32, 34], dtype=int64)

In [117]:
t_x =  []
for k in range(len(test_x)):
    temp = []
    for i in t:
        total = i[:, 0].reshape(-1, 1)
        for j in range(1, 20):
            total = np.row_stack((total, i[:, j].reshape(-1, 1)))
        temp.append(total.reshape(-1))
    temp = np.array(temp).reshape(-1)
    t_x.append(temp)
t_x = np.array(t_x)

In [129]:
t_x[0]

array([10869.56327376, 10869.78679119, 10869.78679119, ...,
        1184.64238552,  1186.02819359,  1184.77649598])

In [119]:
x[0].shape

(51000,)

In [124]:
classifier.fit(x, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=30,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [125]:
classifier.predict(t_x)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [122]:
scores2 = cross_val_score(classifier, x, y)

D:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


ValueError: n_splits=3 cannot be greater than the number of members in each class.

In [75]:
scores2

array([0.08333333, 0.08333333, 0.08333333])